version: '3.8'
services:
  csvserver:
    image: infracloudio/csvserver:latest
    container_name: csvserver
    volumes:
    - ./inputFile:/csvserver/inputdata
    env_file:
    - csvserver.env
    environment:
    - CSVSERVER_BORDER=Orange
    ports:
    - "9393:9300"
